### ISSUE TITLE
auto không hoạt động rồi bro.

### ISSUE THREAD

**Issue by chinhnhguyen090** [tqk2811/AutoCheckinGI#1]
từ đầu tháng tới giờ nó tự checkin được 7 ngày, hnay là ngày 11 thì nó không tự checkin trong 4 ngày rồi. hình như sau khi cái event điểm danh nhận thẻ  tháng xong là nó không checkin được nữa

**Comment by tqk2811** [comment]
Của mình vẫn đều đều, xem có phải là bản mới nhất chưa. Có bị đá login trên web không?  

![image](https://user-images.githubusercontent.com/13986296/195048136-06c874b7-aa03-437f-9ddf-ae0f27e622c1.png)
